### ISSUE TITLE
The docs for the /weather endpoint are outdated.

### ISSUE THREAD

**Issue by koddsson** [apis-is/apis#281]
The docs for the `/weather` endpoint do not state, for example, that it requires a station id number in the request.

**Comment by koddsson** [comment]
Also the JSON scheme for the endpoint is a tad bit confusing.

**Comment by benediktvaldez** [comment]
Actually it does state that [defining stations is required](http://docs.apis.is/#endpoint-weather)
![](http://drop.bdvs.info/1kviR/3ZGfFUCj+)

But I agree that the scheme makes literally no sense (tad bit confusing is putting it mildly IMHO), except maybe to some weather people.. It reflects the data as provided by the XML (which comes with PDF instructions, at least the last time I checked :sigh:) instead of being consumer driven; transforming the objects into something human-readable, which would be the true benefit of using this instead of the official one (IMHO APIs.is should, when applicable ofc, do more than just `xml2js`)

This
```
{
  "name": "Reykjavík",
  "time": "2013-09-17 16:00:00",
  "err": "",
  "link": "http://en.vedur.is/WeatherServlet/weather/observations/areas/reykjavik/#group=100&station=1",
  "F": "8",
  "FX": "9",
  "FG": "16",
  "D": "NNE",
  "T": "5.6",
  "W": "",
  "V": "",
  "N": "",
  "P": "1003",
  "RH": "58",
  "SNC": "",
  "SND": "",
  "SED": "",
  "RTE": "",
  "TD": "-2.0",
  "R": "0.1"
},
```
Should look more like this
```
{
  "name": "Reykjavík",
  "stationId": 1,
  "valid": 1,
  "timestamp": 1460079976605,
  "link": "http://en.vedur.is/WeatherServlet/weather/observations/areas/reykjavik/#group=100&station=1",
  "windSpeed": "8",
  "topWindSpeed": "9",
  "topWindGust": "16",
  "windDirections": "NNE",
  "airTemperature": "5.6",
  "weatherDescription": "",
  "visibility": "",
  "cloudCover": "",
  "airPressure": "1003",
  "humidity": "58",
  "snowDescription": "",
  "snowDepth": "",
  "snowType": "",
  "roadTemperature": "",
  "dewLimit": "-2.0",
  "precipitation": "0.1"
},
```
We could even look at things like `feelsLike`, which is a value that takes air temperature, humidity and wind into account to predict a more useful (and human-readable) value than the three apart (wtf does 58% humidity even mean?)

Only thing that has been holding me back from 'fixing' this, is backwards compatibility; I'm afraid of breaking whatever could be using this endpoint atm. Which brings us back to how useful usage logs would be right now 😄 And the topic of versioning. #fml

Thoughts on how to proceed @koddsson ?

**Comment by koddsson** [comment]
Ah oops! I was reading this and didn't realize that there was a continuation:

![image](https://cloud.githubusercontent.com/assets/318208/14380563/a4395884-fd6f-11e5-8f09-b22fadea816e.png)

In regards to versioning, I'm thinking about doing something small that works for now. Maybe adding routes as we go along with "major" changes. So if we were to change this to the format you suggested, we'd add a `/v2` subroute and leave the original `/` route be, possibly adding a `/latest` route that will always point to the latest version route?

**Comment by benediktvaldez** [comment]
@koddsson sounds similar to what I've been considering - start with something simple and see how it goes

**Comment by valgeirb** [comment]
Hijacking for one moment: Is it normal that the endpoint can return an empty string for the 'W' property (Weather description)?

**Comment by benediktvaldez** [comment]
@valgeirb I've been looking at the [docs](http://www.vedur.is/um-vi/vefurinn/xml/) for the XML-service that we are parsing, and in at least one of their valid examples `W` is indeed an empty string 

Check out [page 6/7 in this pdf](http://www.vedur.is/media/vedurstofan/XML-thjonusta-vedurspar.pdf)

**Comment by valgeirb** [comment]
Strange...thank you @benediktvaldez
