### ISSUE TITLE
Search for bus routes.

### ISSUE THREAD

**Issue by oddsson** [apis-is/apis#374]
In the bus app, you can search for routes via bus from point a to point b. I would much welcome such an endpoint in my life 🚌

**Comment by Joddsson** [comment]
Yes, that sounds about right. 

One thing; The directions array is sorted so that the route that gets you to your destination first comes first. That means that even though route A to C is shorter than route B to C, route B to C comes before A to C if that route gets you to your destination before route A to C does.

**Comment by koddsson** [comment]
Sounds like a good endpoint. I wonder if we should scrape the bus.is website or try to see what endpoint the app is hitting and try to wrap that?
